# Generated by Django 5.2.7 on 2026-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_company_name_remove_user_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_size',
            field=models.CharField(choices=[('small', 'Small (1-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (200+)')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
